Update JenkinsFile

diff --git a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
--- a/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
+++ b/java-maven-sonar-argocd-helm-k8s/spring-boot-app/JenkinsFile
@@ -79,11 +79,18 @@ pipeline {
                     git config --global user.name "hackingquest"
                     BUILD_NUMBER=${BUILD_NUMBER}
                     sed -i "s|abhishekf5/ultimate-cicd:[0-9]*|hackingquest/ultimate-cicd:${BUILD_NUMBER}|g" java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                  
+                     
                     git config --global --add safe.directory /var/lib/jenkins/workspace/first_pipeline
+                    git checkout main || git checkout -b main
                     git add java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
-                    git commit -m "Update deployment image to version ${BUILD_NUMBER}"
-                    git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
+                     # 3. Check if there are actually changes to commit (prevents pipeline failure if no change)
+                     if ! git diff-index --quiet HEAD; then
+                       git commit -m "Update deployment image to version ${BUILD_NUMBER}"
+                       # 4. Push back to your repository
+                       git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
+                     else
+                       echo "No changes detected in deployment.yml, skipping commit."
+                     fi  
                 '''
             }
         }
